### ISSUE TITLE
Make tooltip more customizable

### ISSUE THREAD

**Issue by denisborovikov** [mohsinulhaq/react-popper-tooltip#1]
Thank you for the library!

My suggestion is to remove the default tooltip layout and classes and provide the tooltip customization through [render prop](https://cdb.reacttraining.com/use-a-render-prop-50de598f11ce) instead of classes.

API may look like:

```js
import styled from 'styled-components';

const Tooltip = styled.div`...`;
const Arrow = styled.div`...`;

<TooltipTrigger
  tooltip={({ styles, arrowStyles, arrowPlacement }) => (
    <Tooltip style={styles}>
      <Arrow style={arrowStyles} data-placement={arrowPlacement}  />
      Hello!
    </Tooltip>
  )}
>
  React?
</TooltipTrigger>;
```

It provides the much more flexible way for tooltip customization.

Thank you!

**Comment by mohsinulhaq** [comment]
Hi @denisborovikov, thanks for the suggestion! I will definitely look into implementing this pattern. Meanwhile, feel free to submit a PR with the changes if you like.

**Comment by denisborovikov** [comment]
Here we go #2
