### ISSUE TITLE
React 17 support

### ISSUE THREAD

**Issue by mtmacdonald** [mohsinulhaq/react-popper-tooltip#101]
Please can we have support for React 17 so I don't get this peer dependency warning when installing in my React 17 projects. Thanks!

npm WARN react-popper-tooltip@2.11.1 requires a peer of react@^16.6.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-popper-tooltip@2.11.1 requires a peer of react-dom@^16.6.0 but none is installed. You must install peer dependencies yourself.

**Comment by mohsinulhaq** [comment]
https://github.com/mohsinulhaq/react-popper-tooltip/releases/tag/v3.1.1
