### ISSUE TITLE
Change tooltip color or theme

### ISSUE THREAD

**Issue by omersname** [mohsinulhaq/react-popper-tooltip#102]
I can't change the color of the tooltip. I can override the css with `!important` but I still have a problem with the arrow styling. For me it's a real problem!

It will be a good idea to add a prop for color of the whole tooltip. Example: `color='#000'` .

Alternatively, add a prop for a theme color if you want a several pre-styled tooltips. Example: `theme='dark'` .

**Comment by mohsinulhaq** [comment]
can you please share a minimal Codesandbox demonstrating what you are trying to do?

**Comment by denisborovikov** [comment]
You can create your own CSS file from scratch or use the default one as an example. Set any styles and colors you want, there's no need to add any props for this purpose.

**Comment by omersname** [comment]
That is a good idea 👍 yet I still think you should add this feature, it will be much simpler for us :) thanks
