### ISSUE TITLE
Issue with types after upgrading to v4.0.0

### ISSUE THREAD

**Issue by licia03** [mohsinulhaq/react-popper-tooltip#112]
**Describe the bug**
After upgrading to v4.0.0 I've been reproducing the following issue with Typescript:
`'node_modules/react-popper-tooltip/dist/cjs/react-popper-tooltip.js' implicitly has an 'any' type.
  Try 'npm i --save-dev @types/react-popper-tooltip' if it exists or add a new declaration (.d.ts) file containing 'declare module 'react-popper-tooltip';`

**To Reproduce**
import { usePopperTooltip } from 'react-popper-tooltip';

**Additional context**
Looking at `package.json` I've the feeling this bug is due to wrong path for "typings":
`"typings": "dist/index.d.ts",`

**Comment by mohsinulhaq** [comment]
@licia03 thanks for raising the issue, it was due an unintended change in tsconfig. I have reverted that change now. Please try out v4.0.1 and let me know if it fixed the issue.

**Comment by licia03** [comment]
Yes now It's working as expected.
Thank you @mohsinulhaq

**Comment by mohsinulhaq** [comment]
awesome! closing the issue then
