### ISSUE TITLE
show error type in Typescript

### ISSUE THREAD

**Issue by uixcrazy** [mohsinulhaq/react-popper-tooltip#116]
**Describe the bug**
I have this issue with version `4.0.1` 
![Screen Shot 2021-02-09 at 10 03 15](https://user-images.githubusercontent.com/16874164/107310159-77bae680-6abe-11eb-8870-ba574804e94c.png)

Can you show me how to fix it?

**Comment by mohsinulhaq** [comment]
Please attach a Codesandbox reproducing this error.

**Comment by uasi** [comment]
I've got the same problem. Here is a repro: https://codesandbox.io/s/20210210-react-popper-tooltip-type-error-repro-6ywvc?file=/src/index.js

**Comment by uasi** [comment]
Updated `csstype@3.0.3` (an indirect dependency via `@types/react`) to `csstype@3.0.6` in the repro and the error disappeard.

@uixcrazy try _removing and re-installing_ `@types/react` and any packages that depend on `csstype`. Simply running `yarn upgrade @types/react` or `yarn upgrade csstype` will not work; run `yarn remove @types/react && yarn install -D @types/react` or equevalent npm commands if you are using npm.

**Comment by mohsinulhaq** [comment]
closing this as it's not an issue from within our lib
