### ISSUE TITLE
Tooltip appears even after mouse leaves the trigger

### ISSUE THREAD

**Issue by afurnell** [mohsinulhaq/react-popper-tooltip#117]
Even if the mouse is not hovering over the trigger element, the tooltip will still appear.

1. Go to the basic example ([here](https://codesandbox.io/s/github/mohsinulhaq/react-popper-tooltip/tree/master/examples/basic?file=/src/index.js))
2. Modify the code to pass { delayShow: 1000 } to usePopperTooltip
3. Hover over the button, then move the cursor away and stop moving it
4. The tooltip still appears, and will stay until the mouse moves again

Ideally, the tooltip should not appear, but it does probably because of the changes in #115 

![image](https://user-images.githubusercontent.com/13780859/108373412-c58ac980-71f7-11eb-91ab-19373c37e702.png)

Windows 10
Chrome, Edge
Latest

**Comment by mohsinulhaq** [comment]
@czabaj we should probably add a mouseleave listener as well on the trigger to clear the timeout. Not sure if that's gonna interfere with the mousemove though.

**Comment by mohsinulhaq** [comment]
@afurnell please try out v4.1.1 and let us know if it fixes your issue

**Comment by afurnell** [comment]
I tried to upgrade and received an error:
`> react-popper-tooltip@4.1.1 postinstall C:\{My Project Path}\node_modules\react-popper-tooltip`
`> husky install`

`'husky' is not recognized as an internal or external command, operable program or batch file.`

I then updated using `--ignore-scripts` and can confirm this issue is fixed. Thanks!

**Comment by mohsinulhaq** [comment]
@afurnell fixed in v4.1.2, thanks for reporting
