### ISSUE TITLE
Tooltip with hover trigger not working on page with scrollbar

### ISSUE THREAD

**Issue by b0hdy** [mohsinulhaq/react-popper-tooltip#118]
**Describe the bug**
When mouse enters trigger element and page has vertical scrollbar and his position is not at top of page then tooltip is flickering and does not remain visible. Problem is probably with function `mouseOutsideRect` and comparing mouse and trigger position: `(pageY || clientY) < Math.floor(top) || (pageY || clientY) > Math.ceil(bottom)`.

**To Reproduce**
https://codesandbox.io/s/white-leaf-094it?file=/src/index.js
https://user-images.githubusercontent.com/18634735/108426708-613e2900-723c-11eb-924b-b7b9096d97dc.mov

**Expected behavior**
Tooltip should remain visible after hover button.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser chrome
 - Version 88

**Comment by mohsinulhaq** [comment]
@czabaj I think using `pageX` instead of `clientX` might solve this? Not sure, can you check?

**Comment by b0hdy** [comment]
I found another bug with hover on trigger element, the problem is only in Chrome (FF and Safari works properly). When mouse enters trigger element from the top of the element then tooltip is flickering again. Property `mouseEvent.clientY` in `mouseOutsideRect` strangely returns mouse position about `1px` less than a `tooltipRect.top`.

Code: https://codesandbox.io/s/objective-volhard-7hktp?file=/src/index.js
Demo: https://user-images.githubusercontent.com/18634735/108590190-73b28280-7362-11eb-8fa1-7ba8de80392c.mov

**Comment by b0hdy** [comment]
I found another bug with hover on trigger element, the problem is only in Chrome (FF and Safari works properly). When mouse enters trigger element from the top of the element then tooltip is flickering again. Property `mouseEvent.clientY` in `mouseOutsideRect` strangely returns mouse position about 1px less than a `tooltipRect.top`.

Code: https://codesandbox.io/s/objective-volhard-7hktp?file=/src/index.js
Demo: https://user-images.githubusercontent.com/18634735/108590190-73b28280-7362-11eb-8fa1-7ba8de80392c.mov

**Comment by mohsinulhaq** [comment]
@czabaj can you check this case with your fix?

**Comment by czabaj** [comment]
@mohsinulhaq just checked it and this problem appears with `top` and `left` properties, decreasing both by 1 pixel is a quick fix. But I don't know _why_ this happens 😕

**Comment by mohsinulhaq** [comment]
wow, pretty weird, let me check it out as well

**Comment by mohsinulhaq** [comment]
https://codesandbox.io/s/serene-voice-7cbco?file=/src/index.js
Chrome: 7px and 8px
Firefox: 9.6px and 10px
Safari: 10px and 10px
🤷‍♂️

**Comment by czabaj** [comment]
@mohsinulhaq forked your test and re-tested https://codesandbox.io/s/sharp-zhukovsky-g65qm?file=/src/index.js

Both Firefox and Safari suffer from the rounding error originating from the fact, that DOMRect supports fractional pixels but MouseEvent not ([although it seems that it shall support fractional pixels too](https://github.com/w3c/pointerevents/issues/107)), but only Chrome reports whole integer difference.

Does that sound like a bug in chromium? Meantime, we could exceed the DOMRect by 1 pixel to fix this issue, OK?

**Comment by czabaj** [comment]
I created an issue in the chromium issue tracker https://bugs.chromium.org/p/chromium/issues/detail?id=1180746

**Comment by mohsinulhaq** [comment]
@czabaj thanks for filing it, I was thinking the same, but I thought first I would consult [StackOverflow](https://stackoverflow.com/questions/66307403/discrepancy-in-google-chrome-between-mouse-event-clienty-and-getboundingclientre).
No problem.

Btw, shouldn't we add/subtract 1 only for Chrome?

**Comment by czabaj** [comment]
@mohsinulhaq I would rather not exceed the DOMRect conditionally, it will increase the complexity, I'm not aware of any way how to test the browser vendor reliably and easily, and increasing the DOMRect by 1 pixel will only cause the Tooltip to hide after the mouse leaves "the Trigger and 1 pixel" which is negligible IMHO.

**Comment by mohsinulhaq** [comment]
hmmm makes sense 👍

**Comment by mohsinulhaq** [comment]
somehow, merging the PR auto-closed this issue

**Comment by mohsinulhaq** [comment]
@b0hdy please try out v4.1.1 and let us know if it fixed your issue.

**Comment by b0hdy** [comment]
@mohsinulhaq works well, thank you.
