### ISSUE TITLE
Scrolling causes overflowing issues

### ISSUE THREAD

**Issue by sami-romdhana** [mohsinulhaq/react-popper-tooltip#122]
**Describe the bug**

When tooltips are placed inside a scrolling area, hovering above them and scrolling produces weird results, namely tooltips remaining open and outside the scrolling area.

**To Reproduce**

[Here is a CodeSandbox with an MRE](https://codesandbox.io/s/damp-butterfly-q7x8n).

**Expected behavior**

When scrolling, tooltips should be closed or at least be hidden when "overflowing" the scrolling area.

**Screenshots**

![Example of result](https://user-images.githubusercontent.com/64911368/110646649-5fbaad80-81b7-11eb-963a-cdcff0ac5b4c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge (Chromium)
 - Version: 89

Please let me know if I can be of further assistance (more details) and my apologies if this issue has a known workaround, I could not find one.

**Comment by mohsinulhaq** [comment]
@czabaj could you please look into it?

**Comment by czabaj** [comment]
I will look into it later, but so far I see 2 problems:

1. wrong positioning of the tooltip,
2. the `isMouseOutside` calculation shall be also triggered by the `scroll` event, where the mouse is not `mousemove` but the content under the cursor is moving.

**Comment by mohsinulhaq** [comment]
@czabaj yes, that's something we didn't have to worry about with mouseleave in earlier versions

**Comment by czabaj** [comment]
As the revert to `mouseleave` mechanism will be a breaking change (popper offset will be private, distance between Reference and the Tooltip will configurable via CSS), I also prepared a fix PR for v.4.

**Comment by mohsinulhaq** [comment]
@sami-romdhana please check out `v4.2.0` and let us know if it solved the issue for you.

**Comment by denisborovikov** [comment]
An escaping tooltip issue can be fixed using `closeOnTriggerHidden: true` or add CSS 
```css
.tooltip-container[data-popper-escaped='true'],
.tooltip-container[data-popper-reference-hidden='true'] {
  visibility: hidden;
}
```

**Comment by sami-romdhana** [comment]
@mohsinulhaq I can confirm that the issue is solved on my end with the latest version, thanks for your quick response and your work !

**Comment by yomansk8** [comment]
@mohsinulhaq @denisborovikov I can also confirm that it solves #123 too, thanks for the good work and reactivity guys 💪
