### ISSUE TITLE
Question: using popper for multiple features

### ISSUE THREAD

**Issue by Lueton** [mohsinulhaq/react-popper-tooltip#124]
Hi!

I would like to use this package for my project. But I need popper for more than just tooltips. 

Here is my question: 
**If i use your package can I use Popper without installing it separately, or do I have to install all the required packages in addition, and if so, does my bundle include both versions of Popper? (In case of that, how can I prevent it?)**

Thanks

**Comment by mohsinulhaq** [comment]
Could you elaborate a bit more? Do you want to use `react-popper-tooltip` as well as `@popperjs/core` in your project?

**Comment by Lueton** [comment]
Exactly! I mean, I could just copy your code, but that doesn't sound like a good solution to me.

**Comment by mohsinulhaq** [comment]
Yes, you can use both the libs without having duplicate packages in your bundle or anything like that.
just add the same version semver of `@popperjs/core` to your project's package.json as used by our lib in our `package.json`.

**Comment by Lueton** [comment]
Thank you! :)
