### ISSUE TITLE
Husky is dev-dependency, but part of postinstall script

### ISSUE THREAD

**Issue by dyst5422** [mohsinulhaq/react-popper-tooltip#130]
**Describe the bug**
Husky is dev-dependency, but part of postinstall script, so you get an error on install like 

npm ERR! code 127
npm ERR! path /Users/jdstewar/gitRepos/uplink-dashboard/node_modules/react-popper-tooltip
npm ERR! command failed
npm ERR! command sh -c husky install
npm ERR! sh: husky: command not found

**To Reproduce**
Try to install react-popper-tooltip

**Expected behavior**
No errors about missing dev-dependencies

**Comment by mohsinulhaq** [comment]
it was an issue in an older version
are you installing the latest version (v4.2.0) and still getting the same issue?

**Comment by dyst5422** [comment]
I believe so. It looks to be an issue in 4.2.0 based on the package.json file https://github.com/mohsinulhaq/react-popper-tooltip/blob/v4.2.0/package.json

**Comment by mohsinulhaq** [comment]
@dyst5422 works for me. Can you please try installing the latest version once again? 
![image](https://user-images.githubusercontent.com/7688231/112620100-196b7c80-8e4e-11eb-86ac-a1074143a7d8.png)

**Comment by mohsinulhaq** [comment]
closing this as resolved

**Comment by distinctdan** [comment]
To add onto this, I can't add husky either because husky requires the package.json to be at the root of the project with the .git folder, which isn't an option for the project I'm on.

Unfortunately, this makes this library impossible to use for me.
