### ISSUE TITLE
Using tooltip as a controlled component ignores delayShow/delayHide

### ISSUE THREAD

**Issue by denisborovikov** [mohsinulhaq/react-popper-tooltip#131]
## How to reproduce 

1. Open a controlled component [example](https://codesandbox.io/s/github/mohsinulhaq/react-popper-tooltip/tree/master/examples/controlled)
2. Add `delayShow: 2000` to the hook options
3. Click `Trigger element` and see `delayShow` works, the tooltip shows with a delay. Click again to hide the tooltip.
4. Click `External control` and see the tooltip shows immediately.

## Problem
In the case of the controlled component, `useControlledState` hook switches internal state immediately,  ignoring `delayShow`/`delayHide`

## Solution
Changes in the external state should trigger `showTooltip`/`hideTooltip` handlers instead of the direct state change.

**Comment by denisborovikov** [comment]
Nevermind, this is probably not an issue. In the case of the controlled component, if the external state changes instantly with no delay, the tooltip state changes instantly as well. 

If dealy required, it should be applied to the external state change. I.e. if the user clicks `External control`, states have to change after a 2000ms delay.

**Comment by adi518** [comment]
I don't see why it can be implemented to work out of the box when the state is controlled.

**Comment by denisborovikov** [comment]
This is by definition of the controlled component. At every moment the external state and the actual state of the tooltip have to match. If we use `delayShow`/`delayHide` with an external state, this won't be true.

**Comment by adi518** [comment]
I see what you mean. Cool. 👍

**Comment by denisborovikov** [comment]
Will do.
