### ISSUE TITLE
display: none on tooltip arrow

### ISSUE THREAD

**Issue by cristiannietodev91** [mohsinulhaq/react-popper-tooltip#132]
**Describe the bug**
Tooltip arrow is keeping by default on display: none

I had to override the .tooltip-arrow class with display: block

**Expected behavior**
the tooltip arrow should be showed when the tooltip is open or it must exist a param whether I want to show the tooltip arrow

**Comment by mohsinulhaq** [comment]
@cristiannietodev91 could you please post a codesandbox showcasing your issue? 
Here's the basic sandbox to fork from: https://codesandbox.io/s/github/mohsinulhaq/react-popper-tooltip/tree/master/examples/basic

**Comment by mohsinulhaq** [comment]
Closing this due to no reproducer being available, feel free to reopen in case it becomes available.
