### ISSUE TITLE
Tooltip does not disappear when fast hovering over multiple setTriggerRef divs.

### ISSUE THREAD

**Issue by fffaria** [mohsinulhaq/react-popper-tooltip#135]
**Describe the bug**
Whenever you have two divs with different setTriggerRef that are close to each other, and when you hover the mouse over them a bit fast, at least one of the tooltips stays visible even after the mouse is not hovering over them anymore.
This may be a bit too specific, but I am using two different setTriggerRefs over a canvas, and they might overlap each other, and very often users can see tooltips when they should not be visible.

**To Reproduce**
https://codesandbox.io/s/floral-sunset-m9fc0?file=/src/index.js
Try to move the mouse fast between both setTriggerRefs in a short period of time. I recommend trying to do a small circle that hovers over both of them at a certain speed.

**Expected behavior**
Tooltips should show whenever the user is hovering over their setTriggerRefs, so they should disappear when the user is not hovering over them.

**Screenshots**
![Screen Shot 2021-05-26 at 16 17 49](https://user-images.githubusercontent.com/9650859/119719269-f4d85480-be3e-11eb-95fe-39b39a94494f.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome
 - Version 90.0.4430.212 (Official Build) (x86_64)
 
Thank you for your time!

**Comment by mohsinulhaq** [comment]
@fffaria in your csb, I see only one trigger, could you please update it to include two of them like in the screenshot?

**Comment by fffaria** [comment]
> @fffaria in your csb, I see only one trigger, could you please update it to include two of them like in the screenshot?

Ops. Forgot to save. CSB updated.

**Comment by mohsinulhaq** [comment]
@fffaria 
![ezgif com-gif-maker](https://user-images.githubusercontent.com/7688231/119720619-d34f8b00-be87-11eb-8412-957ed0e8fa17.gif)
looks fine to me, could you send a gif explaining what's happening on your end?

**Comment by denisborovikov** [comment]
I can reproduce the described behavior. @mohsinulhaq You need to _small_ circles in the area near the tooltip's arrows elements.

**Comment by mohsinulhaq** [comment]
great! @denisborovikov 
are you taking this up?

**Comment by denisborovikov** [comment]
@mohsinulhaq I'll try to take the next weekend. Feel free to pick it up If you're able to make it earlier.

**Comment by mohsinulhaq** [comment]
@denisborovikov sure!

**Comment by fffaria** [comment]
Here is how usually happens to me. I know it's very specific, but this glitch is very common when you have a small bar in a chart and the user hovers over them at a certain speed.
https://user-images.githubusercontent.com/9650859/119721975-2f8fbc00-be42-11eb-98f7-e20799b86372.mp4

**Comment by mohsinulhaq** [comment]
@fffaria I think the issue is happening because you have put the function calling the hook in the same component that would re-render and re-create the hook. I took the content out into the component so that the hook isn't re-created from the scratch on re-render, and it seems the issue's fixed.

https://codesandbox.io/s/hopeful-blackwell-ztck1?file=/src/index.js

(Also, since you're already passing `visible` and `onVisibilityChange` prop, you don't really need to add the `onMouseEnter` and `onMouseLeave` on the trigger yourself. The lib does that by itself.)

**Comment by fffaria** [comment]
That indeed fixed the issue. Thank you @mohsinulhaq !
