### ISSUE TITLE
Unable to stop propogation in react-tooltip

### ISSUE THREAD

**Issue by vineethasok** [mohsinulhaq/react-popper-tooltip#137]
I have a nested component with the react-popper-tooltip
When I right click the innermost contextmenu the outermost contextmenu is also opening
I tried e.stopPropogation and e.stopImmediatePropagation in onClick and onContextMenu 
But it is still opening the outermost element
Any tips or workaround are appreciated

**Comment by mohsinulhaq** [comment]
Can you create a codesandbox where I can see the issue in action?

**Comment by vineethasok** [comment]
https://codesandbox.io/embed/determined-frog-j6s6q
Click on the bottom content
It will open 2 tooltip

**Comment by mohsinulhaq** [comment]
@vineethasok to get nested tooltips working, you would have to use the null trigger and implement the outside click handling yourself. 
If you want to quickly create nested tooltips, you should consider v3 of the library (https://github.com/mohsinulhaq/react-popper-tooltip/blob/v3/README.md). v4 moved to a much simpler model with hooks.

**Comment by mohsinulhaq** [comment]
Closing this as resolved.
Feel free to re-open if needed.
