### ISSUE TITLE
Type check error with Typescript 4.4 exactOptionalPropertyTypes 

### ISSUE THREAD

**Issue by gunters63** [mohsinulhaq/react-popper-tooltip#140]
**Describe the bug**
Applying getTooltipProps on a div gives an error with Typescript 4.4 when the (recommended) new option [exactOptionalPropertyTypes](https://www.typescriptlang.org/tsconfig#exactOptionalPropertyTypes) is set.

**To Reproduce**

- Upgrade Typescript to 4.4.
- Add: ` "exactOptionalPropertyTypes": true,` to tsconfig.json
- Style a `div` with ` {...getTooltipProps(...)}`

**Expected behavior**
No type check error

**Screenshots**
![image](https://user-images.githubusercontent.com/90346/131297308-6cf06956-e2a6-482f-b892-e41280c176bc.png)

**Desktop (please complete the following information):**
 - Windows 10
 - Newest chrome

**Comment by JuanJo4** [comment]
i'm facing a similar issue, see #144 .

were you be able to know what was happening?

**Comment by gunters63** [comment]
I had to disable the Typescript error :) Hopefully the author looks into it.

````     
        // Todo: remove after bug is fixed: https://github.com/mohsinulhaq/react-popper-tooltip/issues/140
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
````

**Comment by mohsinulhaq** [comment]
Hi, could you please check if this same happens with `v4.4.0`?

**Comment by gunters63** [comment]
@mohsinulhaq: Sorry only saw this now :)
Yes, the error went away. I am using  4.4.2 now.

**Comment by mohsinulhaq** [comment]
@gunters63 great, thanks!
