### ISSUE TITLE
Typescript error when using `getTooltipProps` in a div

### ISSUE THREAD

**Issue by JuanJo4** [mohsinulhaq/react-popper-tooltip#144]
**Describe the bug**
Typescript error when using `getTooltipProps` in a div.

**To Reproduce**
1. Use the returned value of `getTooltipProps` and use it in a div.
2. Then you will TS error.

Typesctipt: 4.4.3
reaact: 16.9.0
@types/react: 16.14.15
csstype: 3.0.9

**Expected behavior**
No Typescript errors.

**Screenshots**
![Screen Shot 2021-11-04 at 2 56 26 PM](https://user-images.githubusercontent.com/811291/140410784-42dd77a1-04cc-405c-b05d-9e8fb5e329f9.png)

**Desktop (please complete the following information):**
 - OS: Mac OS Monterrey
 - Browser chrome
 - Version 95.0.4638.69

**Comment by hendriklammers** [comment]
I'm facing this exact same issue right now. Initially I thought it might be due to my implementation or incorrect usage of this library, however when trying to convert the basic example provided here in the docs I get the exact same error.

**Comment by mohsinulhaq** [comment]
Hi, could you please check if this same happens with `v4.4.0`?

**Comment by mohsinulhaq** [comment]
Closing as per https://github.com/mohsinulhaq/react-popper-tooltip/issues/140#issuecomment-1268159587
