### ISSUE TITLE
Horizontal scrollbar appears, tooltip is cropped

### ISSUE THREAD

**Issue by moroshko** [mohsinulhaq/react-popper-tooltip#151]
**Describe the bug**
Think of a menu that has items in it. One of the items is disabled and has a tooltip using `react-popper-tooltip`.
The menu is positioned absolutely. (and, this is something I cannot change since it's coming from a 3rd party library `@szhsin/react-menu`)

The undesired effect that occurs is that a horizontal scrollbar appears and the tooltip appears to be cropped.

![react-popper-tooltip-crop-issue](https://user-images.githubusercontent.com/259753/164627640-feac3cfb-4b05-418c-b0f1-d480df4a022d.gif)

**To Reproduce**
[CodeSandbox](https://codesandbox.io/s/react-popper-tooltip-crop-issue-9syzh4?file=/src/index.js)

**Expected behavior**
No horizontal scrollbar, the tooltip is fully visible:

<img width="395" alt="Screen Shot 2022-04-22 at 5 34 57 pm" src="https://user-images.githubusercontent.com/259753/164628888-27fd4c7f-64dc-4bfc-8439-ba1f2ccd891d.png">

**Desktop (please complete the following information):**
 - OS: iOS 12.1
 - Browser: Chrome 100
 - Version: 4.3.1

**Comment by denisborovikov** [comment]
To resolve this issue you have to move the tooltip outside of the parent container. See our demo section - Using with react portal. [Source](https://github.com/mohsinulhaq/react-popper-tooltip/blob/master/examples/portal/src/index.js).

**Comment by moroshko** [comment]
Perfect, thanks a lot!
