### ISSUE TITLE
Is not possible to pass a strategy

### ISSUE THREAD

**Issue by SaraRavasio** [mohsinulhaq/react-popper-tooltip#157]
**Describe the bug**
I have a case where my tooltip is in a div that has overflow and is very small, and my tooltip is not visible.

https://user-images.githubusercontent.com/33936661/176223905-afa0db08-edc2-4cfe-bf3b-db21dbb92b44.mov

I already leveraged the property `strategy = 'fixed'` when using the hook `usePopper` and in the [documentation for tooltip](https://www.npmjs.com/package/react-popper-tooltip) seems that we could do the same, I imagined this meaning that I could pass `strategy` in the same way as I'm passing `placement` or `offset`, but there's no reference of it in the types or anywhere else in the hook.

<img width="817" alt="image" src="https://user-images.githubusercontent.com/33936661/176223470-21bc55b4-d153-4938-b85c-2ad600270861.png">

How can I solve this?
Thanks

**To Reproduce**
Try to pass `strategy: 'fixed'` as a param in `usePopperTooltip`

<img width="1311" alt="image" src="https://user-images.githubusercontent.com/33936661/176224430-134a85ae-770e-4cba-8118-d04a502dfdbe.png">

**Expected behavior**
I can pass `stategy` as a value

**Comment by mohsinulhaq** [comment]
https://github.com/mohsinulhaq/react-popper-tooltip/blob/master/src/usePopperTooltip.ts#L34
popper.js options are to be passed as the second argument to the hook.
Could you please try that?

**Comment by SaraRavasio** [comment]
> https://github.com/mohsinulhaq/react-popper-tooltip/blob/master/src/usePopperTooltip.ts#L34 popper.js options are to be passed as the second argument to the hook. Could you please try that?

ah interesting! i have to say, from the documentation it wasn't very clear, because i can pass `placement` and `offset` in the `config` and therefore it was a bit confusing because from the docs they should be passed in the same way.

also, if I check the type `PopperOptions` i don't see `strategy` as an option.

```
const { getTooltipProps, setTooltipRef, setTriggerRef, visible } =
    usePopperTooltip(
      { placement, offset, ...popperConfig },
      { strategy: 'fixed' }
);
```

but this works indeed, thanks! 😄

**Comment by mohsinulhaq** [comment]
Glad it worked! We kept placement and modifiers there in the first arg for convenience as they are very often used. Rest needs to go in the second arg.
