### ISSUE TITLE
Is it possible to keep the tooltip in the DOM in order to reuse it?

### ISSUE THREAD

**Issue by Tsury** [mohsinulhaq/react-popper-tooltip#21]
I have a pretty massive component under a tooltip, and I want it to stay in the DOM to prevent unneeded re-renders. How is this achievable if at all?

**Comment by mohsinulhaq** [comment]
With current architecture, the tooltip component unmounts on hide and remounts on show, so it's not possible to just `display: hidden` the tooltip, but I can add a prop to toggle this behaviour.

**Comment by mohsinulhaq** [comment]
This feature seems to be requiring quite some changes to code, feel free to raise a PR in case I am late to take this feature up.

**Comment by denisborovikov** [comment]
We just released the hook version of the library. Check out our examples section on how you can implement this feature.
