### ISSUE TITLE
Detecting clicks outside of a tooltip - touch devices (iOS only?)

### ISSUE THREAD

**Issue by olekbruks** [mohsinulhaq/react-popper-tooltip#34]
This issue is related with detecting clicks outside of a opened tooltip which has its "trigger" property set to "click".
Currently this feature doesn't work on Safari Mobile/web view in iOS app.
In my opinion the code should detects events such as "touchstart" (or maybe "touchend") and "auxclick".
I'm not sure if attaching additional listener should be done in this code
```js
_addOutsideClickHandler = () => {
    document.addEventListener('click', this._handleOutsideClick);
    document.addEventListener('touchstart', this._handleOutsideClick);
}
```
or added as a new function.

**Comment by mohsinulhaq** [comment]
Before deploying I did try it on Chrome on Android. So it must be iOS only.
https://81loppjjpl.codesandbox.io
Above is a sandbox with `touchstart` outside click detection enabled. I don't own an iPhone, so could you please check if this works there?
Thanks.

**Comment by olekbruks** [comment]
This issue is iOS only. I've tested the sandbox and it works in Safari on iOS 12 and in Chrome on Android however after some testing I think that listening on `touchend` will work better because of scrolling/ panning. 
I'm unable to test it on iOS 9 because the sandbox renders as a blank page, but this is probably unrelevant.

**Comment by mohsinulhaq** [comment]
I am not sure what do you mean by scrolling/panning. Could you please elaborate?

**Comment by mohsinulhaq** [comment]
okay got it, sounds reasonable. Will replace touchstart with touchend when I get back, and make a stable release. By the way the version with `touchstart` is available as `react-popper-tooltip@2.7.3-alpha.0`

**Comment by mohsinulhaq** [comment]
Looks like there is a bug now due to this change because of which touching trigger doesnt toggle tooltip, but rerenders it. Will need to fix this before stable release.

**Comment by mohsinulhaq** [comment]
https://1zpljm21y4.codesandbox.io
@olekbruks can you try this one both on ios and pc?

**Comment by olekbruks** [comment]
I've tested the solution from the latest _codesandbox_ and it works on Safari on iOS 12 and on Chrome on Android and Windows.

**Comment by mohsinulhaq** [comment]
```
yaay!
```

**Comment by mohsinulhaq** [comment]
The relevant changes are in v2.7.4. You can try it out and close this ticket.
Thanks.

**Comment by mohsinulhaq** [comment]
Assuming the fix worked, I am closing this issue. Feel free to open again if needed.

**Comment by olekbruks** [comment]
Indeed, it works. Thanks.
