### ISSUE TITLE
Code question: why do you use `?` and `!`?

### ISSUE THREAD

**Issue by elie222** [mohsinulhaq/react-popper-tooltip#37]
Asking purely out of interest. while reading your code I was wondering if there was a reason for adding a `?` to your private methods?

```ts
private handleOutsideClick?
```

This also causes you to do this later on which would not be needed if you didn't use `?`.

```ts
this.handleOutsideClick!
```

**Comment by mohsinulhaq** [comment]
https://github.com/mohsinulhaq/react-popper-tooltip/blob/master/src/Tooltip.tsx#L56

I remove the handler from tooltip instance here, this is useful when a nested tooltip closes because parent trigger is out of boundary.

**Comment by elie222** [comment]
Thanks for the explanation!
