### ISSUE TITLE
Tooltip hide on disabled input doesn't work

### ISSUE THREAD

**Issue by denisborovikov** [mohsinulhaq/react-popper-tooltip#41]
If the trigger element is a disabled button, the tooltip isn't hiding on mouse leave.

Demo: https://codesandbox.io/s/61yv95m533

![hover](https://user-images.githubusercontent.com/831065/51524426-ff4a4400-1e68-11e9-858f-843d51e80736.gif)

**Comment by mohsinulhaq** [comment]
This is a known issue with React on Chrome and Safari, where `mouseenter` is triggered on disabled elements but not `mouseleave`. This however, should work fine in Firefox.

Ref: https://github.com/facebook/react/issues/4251

**Comment by denisborovikov** [comment]
Seems it's going to be fixed in coming React 16.3.0

**Comment by mohsinulhaq** [comment]
@denisborovikov yeah, I had asked here https://github.com/facebook/react/pull/17675#issuecomment-591637136 just to be sure it's the exact same issue.

**Comment by mohsinulhaq** [comment]
They have now closed the issue. I guess we can close this one as well, as I can see that your sandbox is working as expected after the upgrade.

**Comment by denisborovikov** [comment]
Huh, now it means we can't even have a tooltip on a disabled button.

**Comment by mohsinulhaq** [comment]
That's what should happen according to HTML spec. If you still want it, you can wrap the button with a div.

**Comment by denisborovikov** [comment]
Sure, or use a fake button as well. Did know it's according to spec.

**Comment by aigoncharov** [comment]
We had the same problem at https://github.com/hazelcast/frontend-shared/issues/58. We ended up using a child component inside of the button as the tooltip trigger.
