### ISSUE TITLE
Click events are magically turned into touch events

### ISSUE THREAD

**Issue by mauricesvay** [mohsinulhaq/react-popper-tooltip#56]
When the browser supports touch events, the `onClick` event is automatically turned into a `onTouchEnd` event:
https://github.com/mohsinulhaq/react-popper-tooltip/blob/master/src/TooltipTrigger.tsx#L208-L215

This is an issue for some laptops with a touch screen that do not trigger `onTouchEnd` when using a mouse.

**Comment by mohsinulhaq** [comment]
Interesting. I think I would need to add both event listeners irrespective of device capability and stop propagation for each to prevent multiple firings.

**Comment by mauricesvay** [comment]
For the moment, I'm patching the behavior on my end by replacing the `onTouchEnd` event by a `onClick` event after calling `getTriggerProps`. 
But I'm still interested in a proper solution. Let me know if I can help.

Thanks for sharing this library!

**Comment by mohsinulhaq** [comment]
are you in possession of that hybrid device?

**Comment by mauricesvay** [comment]
@mohsinulhaq unfortunately no, it's been reported by a user.

**Comment by mohsinulhaq** [comment]
Hi, I have released v2.8.1-alpha.0 which has a potential fix.
Please try it out. If it works fine, I will release a stable version.
Thanks.

**Comment by mohsinulhaq** [comment]
Hi, any update?

**Comment by mauricesvay** [comment]
I’ll try to test again with the customer this week. Thanks for helping on this issue 🙏

Envoyé de mon iPhone

**Comment by mauricesvay** [comment]
Hi, sorry for the late reply, but I can confirm that 2.8.1-alpha.1 fixes the issue. Looking forward to the next release. Thanks a lot for your help!

**Comment by mohsinulhaq** [comment]
Fix now available in [v2.8.1](https://github.com/mohsinulhaq/react-popper-tooltip/releases/tag/v2.8.1)
