### ISSUE TITLE
Problems with `touchend` event handling

### ISSUE THREAD

**Issue by olekbruks** [mohsinulhaq/react-popper-tooltip#58]
Unfortunately, a fix that I suggested for the issue #34 together with a fix for the #56 introduces some serious issues with handling `click` events triggered from control inside a tooltip. 

On a mobile device that supports both `click` and `touchend` events `touchend` "outside click" handler intercepts all events, eg. `click` on a button inside the tooltip.

https://codesandbox.io/s/6xwrm2zxrr

**Comment by mohsinulhaq** [comment]
So what's happening is that clicking on "Clickable `div`" closes the tooltip on iOS?

**Comment by olekbruks** [comment]
The problem is that nothing happens when you click on "Clickable div" - the `touchend` event handler will prevent any other event handlers from being fired (`event.stopPropagation()`), even the `click` event handler attached to the "Clickable div".

I mean every smartphone/tablet. When you attach both `touchend` and `click` to a `div` both will be called. The only exception is `document`, `div` or other semantically unclickable HTML element in iOS. I know that the popular fix for this behavior is using `cursor: pointer` on that element. Maybe instead of handling `touchend` the solution is to use CSS? I will check it tomorrow.
```css
html, body {
    cursor: pointer;
}
```

**Comment by mohsinulhaq** [comment]
I have published `v2.8.2-alpha.0` which uses [Pointer Events](https://developer.mozilla.org/en-US/docs/Web/API/Pointer_events)  instead of click and touchend events.
Please give it a spin.

**Comment by mohsinulhaq** [comment]
https://github.com/facebook/react/issues/12901
just came to know that safari doesn't support pointer events
tough luck

**Comment by olekbruks** [comment]
Hmm, I do not know how to fix this issue yet. I will be grateful if you release a version with all the recent fixes but those related to touch events (#34).

Later I investigate if using `cursor: pointer` is good enough.

**Comment by mohsinulhaq** [comment]
For you 2.8.0 was fine. You can pin to that version until a proper fix is in place.

**Comment by olekbruks** [comment]
Thanks for quick reply.

Unfortunately my customers are using IE, so I need this commit: https://github.com/mohsinulhaq/react-popper-tooltip/commit/0a7c9ab94b9bc5e2ac3b5bb866d6a5d9b2afc6fc 

I could make a fork of this repo, but I do not know how to build it.

**Comment by mohsinulhaq** [comment]
Oh ok then. I will release an alpha version for you with the change you need. No issues.

**Comment by mohsinulhaq** [comment]
Published as 2.8.2-alpha.1

**Comment by mohsinulhaq** [comment]
please confirm if the version suffices, so that we can close this issue.

**Comment by olekbruks** [comment]
Thanks for the alpha version release, but changes related to handling touch events (0e25264ab771b7cca7b86dcff839de57c6181672) are still in the code of this release, so popovers with `click` trigger don't work on hybrid devices such as a notebook with touch screen.

**Comment by mohsinulhaq** [comment]
As you might have noticed, I don't have a solution yet that can suffice both yours as well as hybrid device use case. To support hybrid device, I definitely need to use stopPropagation and preventDefault to stop click handler and touch handler calling each other. If you have one, please feel free to raise a PR.

**Comment by mohsinulhaq** [comment]
Hey bro, could you please help me out and tell me if v2.8.2 solves your use case. I saw that removing `preventDefault` from *only* the outside click handler makes your example as well as an example from another issue work. It would be great if you can confirm from your side.

**Comment by olekbruks** [comment]
Look like that everything is ok! I will wait for the response from the test team.
