### ISSUE TITLE
Problem with compilation

### ISSUE THREAD

**Issue by bogdansoare** [mohsinulhaq/react-popper-tooltip#6]
Using create-react-app I get this error

```
Failed to minify the code from this file:

        ./node_modules/react-popper-tooltip/dist/TooltipTrigger.js:1:1460
```

https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify

**Comment by mohsinulhaq** [comment]
ok, so we were initially targeting only modern browsers that support ES6. But we can change that to suppprt ES5 aa well.

**Comment by bogdansoare** [comment]
I understand that you want to support only the latest browsers, but that would mean leaving out all the users of create-react-app and maybe other similar tools

**Comment by mohsinulhaq** [comment]
https://github.com/mohsinulhaq/react-popper-tooltip/releases/tag/v2.2.1
Released a new version with support for many more browsers. Please try it out. CRA build is fine now.
Let me know if there are any issues, otherwise, we can close this.

**Comment by bogdansoare** [comment]
cool, thank you for the fast response 🙏, CRA build is good now
