### ISSUE TITLE
Links inside tooltip

### ISSUE THREAD

**Issue by elias-fadeyev** [mohsinulhaq/react-popper-tooltip#60]
### Reproduction demo

https://codesandbox.io/s/1q9yy1342j

### Steps to reproduce the problem

1. Click on the trigger
2. Click on the link

### What is the expected behavior?

I think `click trigger` should allow events inside the tooltip

### What went wrong?

The link doesn't follow the URL.
`Click on the link` triggers `_this.handleOutsideClick()` and then it calls `event.preventDefault()`.

### Any other comments?

Do we have any possibility to avoid this?
Or wouldn't it be a good idea to add `outsideClickHandler` to props?

### Packages versions

- react-popper-tooltip: 2.8.1

**Comment by mohsinulhaq** [comment]
Pleas try out v2.8.2 which has a potential fix.

**Comment by elias-fadeyev** [comment]
Now it works, thank you!
As a related issue, is it possible to change `click` listener to `mousedown` for `outsideClickHandler`? We use this tooltip inside a drag'n'drop container and, if we move the container, `outsideClickHandler` doesn't trigger and, as a result, the tooltip stays shown outside of the container.

**Comment by mohsinulhaq** [comment]
Does it close when you drop the container?

**Comment by elias-fadeyev** [comment]
No, in our case `click` is not triggered after dropping and it stays opened, only `mouseup` is fired.

**Comment by mohsinulhaq** [comment]
I attach a outside `click` handler to `document`, whenever the tooltip opens. Do you know how is that not triggered? Is your mouseup or mousedown handler stopping propagation to the click handler?

**Comment by elias-fadeyev** [comment]
Yep, we are using `react-sortablejs` and it seems that it stops propagation inside `mouseup` handler, if an order of elements has been changed. That's why we don't have `click` event now, but I think it's not a big deal. I mean isn't it a strange behavior of a tooltip to stay at the same place, when the container is moved to an opposite side of the window, even if it will be hidden after that?

**Comment by denisborovikov** [comment]
@elias-fadeyev Did you try to play with usePortal/portalContainer props? Tooltip can be attached to the draggable element instead of the document body. In this case, it should move with the appropriate container.

**Comment by elias-fadeyev** [comment]
@denisborovikov. Agree, but then this tooltip will be restricted to have the body only inside the container. It won't work for a big tooltip.

**Comment by denisborovikov** [comment]
@elias-fadeyev Does outer container has `overflow: hidden`? You can try to apply `overflow` on the inner part of the draggable element so the mutual wrapper won't cut the tooltip.

**Comment by elias-fadeyev** [comment]
@denisborovikov my fault, you are absolutely right! Unfortunately, a big tooltip now works as a handle and I can use it to drag'n'drop the container, as a part of it) I'll try to find the solution for preventing this behavior. Thank you
