### ISSUE TITLE
The modifiers object doesn't seem to be exposed to Popper.JS?

### ISSUE THREAD

**Issue by smksnutmeg** [mohsinulhaq/react-popper-tooltip#61]
**Describe the bug**

**Expected behavior**
I should be able to set:
```
  <TooltipTrigger
    placement={placement}
    usePortal={false}
    trigger={trigger}
    modifiers={{
      offset: 10
    }}
```

but modifiers does not get passed through in source.

**Comment by mohsinulhaq** [comment]
Modifiers do get passed to Popper.JS here: https://github.com/mohsinulhaq/react-popper-tooltip/blob/master/src/TooltipTrigger.tsx#L93

And offset modifier is an object like any other modifier, rather than a number. 
https://popper.js.org/popper-documentation.html#modifiers..offset

**Comment by denisborovikov** [comment]
As @mohsinulhaq  mentioned, it should be 

```
 <TooltipTrigger
    placement={placement}
    usePortal={false}
    trigger={trigger}
    modifiers={{
      offset: {offset : 10}
    }}
```

**Comment by lucasreppewelander** [comment]
Nowadays it seems that the modifiers is no longer an object but an array and thus the very same here above would look like this:
```
modifiers={[
    {
        name: 'offset',
        options: {
            offset: [0, 2],
        },
    },
]}
```
