### ISSUE TITLE
Is it possible to render html content inside the tooltip?

### ISSUE THREAD

**Issue by erkaner** [mohsinulhaq/react-popper-tooltip#62]
I wonder if it is possible to turn on rendering html content inside the tooltip. For example, I want to add a header and a paragraph. When I do it now, all rendered as string. I wonder if you consider to implement an option to turn on html-rendering. Thanks!

**Comment by mohsinulhaq** [comment]
It is quite possible to do html rendering using JSX.
Could you please post your usage here?

**Comment by erkaner** [comment]
It was my mistake. Thanks for the answer!
