### ISSUE TITLE
Ability to close tooltips on Escape key

### ISSUE THREAD

**Issue by brookback** [mohsinulhaq/react-popper-tooltip#7]
Hey! Thanks for a great package 💞 It vastly simplified me working with Popper and creating dropdowns!

One thing that's kinda common for popovers/dropdowns is to close them on <kbd>escape</kbd> key. Could this fit into this package, you think?

The requirements could be something like:

- Make it close on `keydown` event, with key <kbd>escape</kbd> as default.
- Provide a way to opt out of the default behaviour (`closeOnEscape: false` as a passed prop).

I guess one can implement support for super custom cases here, like the ability for consumers to decide what DOM event and what key should trigger the close, but I think it'd be nice to keep it simple for now.

Let me know if I can help out with a PR.

I've implemented a quick fix in a fork of mine in the meantime, which code you can view here: https://github.com/brookback/react-popper-tooltip/pull/1.

**Comment by denisborovikov** [comment]
Hi, thank you for the idea and the code!

As for me, I'd like to keep the library simple and flexible and avoid adding custom cases.

You can implement the same behavior with a current API. Here's an example (I used the part of your code there) https://codesandbox.io/s/v04l1ky2rl

I took a Tooltip wrapper from our README example and added only innerRef prop support. TooltipClick implements the rest functionality.

**Comment by brookback** [comment]
@denisborovikov Thanks for the reply and quick code writeup ✨ That seems to work out well.

Btw, the sample code doesn't seem to function – need to do this in `Tooltip.js`:

```diff
-innerRef={this.myRef}
+innerRef={this.tooltipRef}
```

Just so others know!

***

I'd be more descriptive of the use of `ref` in the README: I completely missed the paragraph

> You also have the ability to attach ref to the TooltipTrigger component which exposes following methods for programmatic control of the tooltip [..]

Perhaps a quick use case? Something that would be really nice would be to have a `recipes` directory with quick code snippets on common use cases, like doing this escape handling, attaching transitions on the popover, etc. Just a thought.

**Comment by denisborovikov** [comment]
Thanks, I refactored the code after I pushed the comment but didn't reload the page. Fixed now.

You're right about the `ref` docs. @mohsinulhaq  wasn't clear enough. I didn't understand this prop at all before I implemented the example above.

We can start the recipes from this case.

**Comment by denisborovikov** [comment]
We're going to remove a ref part from README. To implement close on Esc feature external state with `tooltipShown` and `onVisibilityChange` should be used.

I will provide an example after #11 merged.

**Comment by mohsinulhaq** [comment]
recipe added
check out https://mohsinulhaq.github.io/react-popper-tooltip
we can close this ticket now

**Comment by dkhirude** [comment]
@mohsinulhaq Is there any documentation available regarding implementing custom triggers ?

**Comment by mohsinulhaq** [comment]
@dkhirude you can use the controlled mode: https://react-popper-tooltip.netlify.app/#controlled
