### ISSUE TITLE
Add looser peer dep requirements for react and react-dom?

### ISSUE THREAD

**Issue by majapw** [mohsinulhaq/react-popper-tooltip#73]
QQ: Would it be possible to loosen the react and react-dom peer dep restrictions to ^16.0.0 or are there explicit dependencies on react 16.6+ features in this library?

**Comment by mohsinulhaq** [comment]
https://github.com/mohsinulhaq/react-popper-tooltip/blob/master/src/Tooltip.tsx#L11
I am using this feature from React 16.6
https://github.com/facebook/react/blob/master/CHANGELOG.md#react-dom-8

**Comment by majapw** [comment]
No worries! Thank you for the quick response.
