### ISSUE TITLE
Exposing the Popper.js instance

### ISSUE THREAD

**Issue by AlexLomm** [mohsinulhaq/react-popper-tooltip#75]
**Is your feature request related to a problem? Please describe.**
I had a need to call the `scheduleUpdate` for the underlying Popper.js instance, but was not able to find any way to do that.

**Describe the solution you'd like**
Will it be possible to expose the original Popper.js instance for the advanced use cases that may not be covered by the native API of the "react-popper-tooltip"?

**Describe alternatives you've considered**
I tried getting around the problem by experimenting with the native API to no avail.

**Additional context**
The problem I'm facing is that I need to reposition the tooltip when its target resizes or moves.

**Comment by mohsinulhaq** [comment]
looking at the [docs](https://github.com/FezVrasta/react-popper), I don't see any way the popper instance itself is exposed. But we can expose `scheduleUpdate` if that's all you need. However, I wonder how that API might look like.
cc: @denisborovikov

**Comment by denisborovikov** [comment]
I think, we should call scheduleUpdate automatically rather than exposing it. I wonder why the mutation observer doesn't work here.

**Comment by mohsinulhaq** [comment]
https://github.com/mohsinulhaq/react-popper-tooltip/blob/master/src/Tooltip.tsx#L5
Because it is only tracking subtree node addition/removal changes. We can further add attribute change detection and ask the OP to change class when the target resizes or moves.

**Comment by denisborovikov** [comment]
We just released the hook version of the library. It exposes `update` and `forceUpdate`.
