### ISSUE TITLE
Clicking the trigger should not stop propagation

### ISSUE THREAD

**Issue by dnizetic** [mohsinulhaq/react-popper-tooltip#76]
Clicking the trigger stops event propagation:

https://github.com/mohsinulhaq/react-popper-tooltip/blob/master/src/TooltipTrigger.tsx#L194

I don't understand why this is the default behaviour. It limits the trigger to only do one thing - open the popup - why impose this limit? If user wants to stop propagation it can easily be done by calling getTriggerProps() and overriding onClick.

I was wandering if we can get the choice of whether clicking the trigger will stop propagation. Not having the option creates an issue for us because in our case, clicking the trigger does a few more things apart from opening the popup, and the onClick event gets stopped due to .stopPropagation call.

**Comment by mohsinulhaq** [comment]
This is added to support hybrid devices with both touch and click support. event.stopPropagation is making sure only one of the event is triggered at a time. Feel free to suggest a better way of handling both touch and clicks.

**Comment by dnizetic** [comment]
So ideally the propagation will only be stopped on mobile devices - any chance this (or some other solution) can make it to release any time soon?

**Comment by mohsinulhaq** [comment]
Please try out v2.9.1 and let me know if everything is fine or not. I have removed the stopPropagation usage.

**Comment by robertedjones** [comment]
This is a breaking change

**Comment by mohsinulhaq** [comment]
@robertedjones Did it break something for you? I had added the same stopPropagation in `v2.8.1`.

**Comment by robertedjones** [comment]
@mohsinulhaq yes i was previously using v2.8.3 without issue but now you have removed stopPropagation I have unwanted events firing. I have tried to override the onClick event using getTriggerProps but can't seem to re-create the functionality from before - do you have any pointers? For now I will roll back to 2.8.3. Thanks

**Comment by mohsinulhaq** [comment]
@robertedjones the behavior currently displayed by the tooltip is consistent with React's philosophy of Potals. See: https://github.com/facebook/react/issues/11387

Regarding
> I have tried to override the onClick event using getTriggerProps

Check this out, this worked fine for me
https://codesandbox.io/s/react-popper-tooltip-example-bq9li

**Comment by robertedjones** [comment]
@mohsinulhaq thanks for the demo, that's what I had tried but it had other knock-on effects which I would need to spend some more time investigating. For now I've rolled back.

**Comment by mohsinulhaq** [comment]
it is possible that there are other click-like events in the container like `mouseDown`.
