### ISSUE TITLE
Add 'focus' trigger

### ISSUE THREAD

**Issue by moonray** [mohsinulhaq/react-popper-tooltip#77]
**Is your feature request related to a problem? Please describe.**
While click and hover are relevant triggers in most cases, the use of focus for triggering the tooltip is sometimes needed when using keyboard navigation.

**Describe the solution you'd like**
Add a 'focus' trigger in addition to the existing click, right-click, and hover triggers.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by mohsinulhaq** [comment]
https://github.com/mohsinulhaq/react-popper-tooltip/issues/59
check this out

**Comment by mohsinulhaq** [comment]
@moonray https://github.com/mohsinulhaq/react-popper-tooltip/releases/tag/2.9.0
Focus trigger is now supported in react-popper-tooltip@2.9.0
