### ISSUE TITLE
[Question/Bug]  React-Window scroll causes tooltip to rerender for no reason.

### ISSUE THREAD

**Issue by iazO** [mohsinulhaq/react-popper-tooltip#79]
**Describe the bug**
We are using React-Window for show casing big lists. Within this big list we often use popper-tooltip to allow for extra visualization of information. 

React-window is smart enough to not rerender any rows which were already rendered once as long as the information does not change.

However, when scrolling in React-window when using these tooltip component ALL tooltip components are rerendered causing performance issues in this list.

It seems like i'm unable to control this component in any way. I did find out when removing the triggerRef on the tooltip wrapper span the problem does not occur (but we also get no tooltip :)). 

```
const Trigger = (children: React.ReactNode) => ({ **triggerRef**, getTriggerProps }: ChildrenArg) => (
  <span
    key="tooltip-span"
    id="tooltip-span"
    {...getTriggerProps({
      ref: **triggerRef**
    })}
  >
    {children}
  </span>
);
```

**To Reproduce**
Use tooltip in a list from react-window. Tried multiple memo possibilities in order for it to not rerender, but the same behavior keeps occurring.

**Expected behavior**
The tooltip should not rerender when there is no cause for it.

**Screenshots**
![image](https://user-images.githubusercontent.com/17141336/66839902-74b1f380-ef67-11e9-8596-d30a23c630aa.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 77.0.3865.120

**Comment by mohsinulhaq** [comment]
Can you please provide a minimal codesandbox for this?

**Comment by iazO** [comment]
Thanks for responding so quickly:
https://codesandbox.io/embed/react-window-meets-tooltip-popper-xheky

The React-Dev tools do not work in the embedded viewer though.

**Comment by iazO** [comment]
I've made a new sandbox which resembles my scenario more https://codesandbox.io/s/boring-https-7nn4b, using infiniteloader. It is still not exactly like in our application, as we do api calls and stuff, but i'm unable to reproduce it in an easy manner.

So i'll close the question for now as i'm not able to properly reproduce it for you in order to have a look. Thanks for your time though!
