### ISSUE TITLE
Support multiple triggers

### ISSUE THREAD

**Issue by itsravenous** [mohsinulhaq/react-popper-tooltip#81]
**Is your feature request related to a problem? Please describe.**
For accessibility it would be nice to be able to show tooltips on hover for mouse users and focus for keyboard users. It doesn't seem like this is currently possible, because only one event type can be passed to the `trigger` prop.

**Describe the solution you'd like**
Support passing multiple triggers to `trigger`. A space-separated string would be fine.

**Describe alternatives you've considered**
A workaround is to manually assign `onFocus` and `onBlur` on our trigger to the `onMouseEnter` and `onMouseLeave` respectively.

**Comment by mohsinulhaq** [comment]
I have released `v2.10.0` with the required support. Please try it out and confirm if it's working fine for you.

**Comment by itsravenous** [comment]
Thank you!
