### ISSUE TITLE
BUG set an array of strings for the trigger prop

### ISSUE THREAD

**Issue by AndreiDogaru** [mohsinulhaq/react-popper-tooltip#82]
**Describe the bug**
When setting the trigger to an array of strings, the hover effect doesn't work properly anymore. If you hover the trigger and move your mouse inside the tooltip, the tooltip disappears.

**To Reproduce**
Go to the code sandbox from your documentation and inside Example.js replace the value of trigger with {["hover"]} or any other array of strings. Then try to move the mouse inside the tooltip.

**Expected behavior**
I would expect this to work the same way as trigger="hover" does.

**Desktop (please complete the following information):**
 - OS: MacOS Mojave
 - Browser Chrome
 - Version 78.0.3904.108 (Official Build) (64-bit)

**Comment by mohsinulhaq** [comment]
Thanks for raising the issue. I will provide a new release with the fix by this weekend. There are some typing issues with the newer versions of `react-popper` which I need to look into.

**Comment by mohsinulhaq** [comment]
`v2.10.1` released with the fix. Please try it out and let me know.

**Comment by AndreiDogaru** [comment]
It works as expected now 👍 

Cheers mate !
