### ISSUE TITLE
Don't close on click when trigger hover

### ISSUE THREAD

**Issue by evandikt** [mohsinulhaq/react-popper-tooltip#85]
Hi,

I want to don't close the tooltip if `trigger='hover'` and user click on the trigger element.

Try here  : https://react-popper-tooltip.netlify.com/#hover-trigger

THX

**Comment by denisborovikov** [comment]
Hi there,

You need to use a tooltip as a controllable component. Check this [branch](https://github.com/mohsinulhaq/react-popper-tooltip/issues/59).

Here's a quick example https://codesandbox.io/s/react-popper-tooltip-example-sc9eq
