### ISSUE TITLE
Upgrade to latest popper packages

### ISSUE THREAD

**Issue by ndelangen** [mohsinulhaq/react-popper-tooltip#94]
**Is your feature request related to a problem? Please describe.**
popper.js v1 has been deprecated

**Describe the solution you'd like**
Upgrading all popper related packages

**Describe alternatives you've considered**
none

**Additional context**
https://github.com/storybookjs/storybook/issues/9961#issuecomment-642539585

**Comment by stof** [comment]
@ndelangen I think this is a duplicate of #92
