### ISSUE TITLE
Could you continue shipping some sensible default CSS?

### ISSUE THREAD

**Issue by lostfictions** [mohsinulhaq/react-popper-tooltip#96]
Hi there, thanks for this library! I just installed the latest version for a new project, but I was a bit confused that the tooltips weren't styled, and the npm module doesn't ship any CSS I can import. I saw in the release notes that this is a recent change.

Given that it's still up to the user to import CSS themselves (and thus that it doesn't add any cost or bloat the bundle size by default) is there any reason you couldn't consider shipping some sensible default CSS with the npm module as a starting point for users? I feel this is the sort of thing that really makes it easier to get up and running with a library quickly. (I also imagine you have to maintain some default CSS for the demo page and example code anyway, so why not just ship it?)

Alternately, if shipping CSS with the package is objectionable for whatever reason, maybe you could consider including a CSS snippet directly in the readme?

**Comment by lostfictions** [comment]
(Incidentally, for any other users landing on this issue because they're confused about styling the tooltip, I just grabbed the [CSS from the last tagged release](https://github.com/mohsinulhaq/react-popper-tooltip/blob/v2.11.1/src/styles.css) -- it seems to work fine.)

**Comment by mohsinulhaq** [comment]
@lostfictions https://github.com/mohsinulhaq/react-popper-tooltip/releases/tag/v3.1.0
here you go! 😃

**Comment by lostfictions** [comment]
Thanks so much!
